name: CI

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.1

      - uses: jdx/mise-action@v4.3.0

      - name: Check formatting and lints
        run: mise run check

      - name: Run tests
        run: cargo test
