name: Coverage

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        run: |
          rustup update stable

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@ba7c31b66a9387b433c77da64cc4d622b341a338

      - name: Generate code coverage (LCOV)
        run: |
          cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de
        with:
          files: lcov.info
          fail_ci_if_error: true
