name: Coverage

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        run: |
          rustup update stable

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate code coverage (LCOV)
        run: |
          cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info --jobs 1 -- --test-threads=1

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad
        with:
          files: lcov.info
          fail_ci_if_error: true
